title: Google Trends Guides
description: Practical guides to getting more out of Google Trends data.
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
webmaster_verifications:
  google: nmVCBuvzjdUckpEaP5WZsf-V6XCH8QEg0Zjt-53tBPM
